services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend-server:
    build:
      context: ../server
    environment:
      - MONGODB_URI=mongodb://mongo:27017/scem-evMan
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  seed:
    build:
      context: ../server
    command: node scripts/seed.js
    environment:
      - MONGODB_URI=mongodb://mongo:27017/scem-evMan
    depends_on:
      - mongo

volumes:
  mongo-data:
